# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20170812_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(default='priv_msg', max_length=15)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.Profile')),
            ],
        ),
    ]
