# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170816_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
